name: ftp_server
description: "Dart FTP server: Read-only/read-write. Clients can list directories, get/put files, and perform standard FTP operations."
version: 2.1.1
homepage: https://github.com/abdelaziz-mahdy/ftp_server

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  intl: ^0.20.1
  path: ^1.9.0
dev_dependencies:
  test: ^1.25.5
  lints: ^5.1.1

